### ISSUE TITLE
Zod error -  react fundamentals

### ISSUE THREAD

**Issue by Command087** [epicweb-dev/get-started-with-react#2]
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "name"
    ],
    "message": "Expected string, received null"
  }
]
    at Object.get error [as error] (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/zod/lib/index.mjs:587:31)
    at ZodEffects.parse (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/zod/lib/index.mjs:692:22)
    at getFreshValue (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/@epic-web/workshop-app/app/utils/epic-api.ts:639:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getFreshValue (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/@epic-web/cachified/src/getFreshValue.ts:17:24)
    at Module.cachified (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/@epic-web/cachified/src/cachified.ts:89:17)
    at file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/remix-utils/build/common/promise.js:30:106
    at async Promise.all (index 3)
    at promiseHash (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/remix-utils/build/common/promise.js:30:31)
    at loader$y (file:///Users/khuthadzomasindi/dev/epic/new-epic/react-fundamentals/epicshop/node_modules/@epic-web/workshop-app/app/root.tsx:106:21) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ]
}

**Comment by kentcdodds** [comment]
I published a bad validation. It should be fixed now. Could you please try again? Thanks!
